---
vm_type: esxi

cpus: 4
ram: 7168
nics:
- name: eth0
  ipv4_address: 192.168.103.21
  ipv4_gateway: 192.168.103.1
  ipv4_netmask: 255.255.255.0
  method: dhcp
  vmnet: vmnet103
- name: eth1
  method: os
  vmnet: vmnet103
disks:
- name: sda
  size: 40GB
- name: sdb
  size: 8GB
- name: sdc
  size: 256GB

vmk_mgmt:
  ipv4_address: 192.168.103.21
  ipv4_gateway: 192.168.103.1
  ipv4_netmask: 255.255.255.0

vmk_vsan:
  ipv4_address:
  ipv4_gateway:
