---
vm_type: vm

cpus: 4
ram: 12288
nics:
- name: eth0
  ipv4_address: 192.168.99.9
  ipv4_gateway: 192.168.99.1
  ipv4_netmask: 255.255.255.0
  method: vmnet
  vmnet: vmnet99
disks:
- name: sda
  size: 64
