---
- name: dhcpd-relay | install the relay server
  yum:
    name: dhcp-relay
    state: present

- name: dhcpd-relay | template out systemd unit file
  template:
    src: dhcrelay.service.j2
    dest: /etc/systemd/system/dhcrelay.service
    owner: root
    group: root
    mode: 0644
  notify: restart dhcrelay

- name: dhcpd-relay | systemd
  systemd:
    name: dhcrelay
    state: started
    enabled: yes
    daemon_reload: yes

- name: dhcpd-relay | flush handlers
  meta: flush_handlers
