---
- name: dnsmasq | install packages
  yum:
    name: dnsmasq
    state: present

- name: dnsmasq | template config
  template:
    src: dnsmasq.conf.j2
    dest: /etc/dnsmasq.conf
    owner: root
    group: root
    mode: 0644
  notify: restart dnsmasq

- name: dnsmasq | systemd
  systemd:
    name: dnsmasq
    state: started
    enabled: yes

- name: dnsmasq | flush handlers
  meta: flush_handlers
