---
- hosts: core_router
  become: yes
  gather_facts: yes
  roles:
  - role: network-interfaces-static
    tags: network
  - role: iptables
    tags: firewall
  - role: dnsmasq
    tags:
    - dns
    - dhcp
  - role: bird2
    tags: bgp
