---
- hosts: '{{ target }}:!localhost'
  become: no
  gather_facts: no
  serial: 1
  roles:
  - role: vmware-fusion/vmx/power-off
    delegate_to: '{{ groups.vmware_fusion_host[0] }}'
  - role: vmware-fusion/vmx/delete
    delegate_to: '{{ groups.vmware_fusion_host[0] }}'
