---
- hosts: core_router
  become: no
  gather_facts: no
  roles:
  - role: vmware-fusion/vmx/power-off
    delegate_to: '{{ groups.vmware_fusion_host[0] }}'
  - role: vmware-fusion/vmx/delete
    delegate_to: '{{ groups.vmware_fusion_host[0] }}'

- import_playbook: create-vm.yaml
  vars:
    target: core_router

- hosts: core_router
  become: no
  gather_facts: no
  roles:
  - role: vmware-fusion/vmx/power-on
    delegate_to: '{{ groups.vmware_fusion_host[0] }}'
  - role: wait-for-ssh

- import_playbook: configure-core-router.yaml
