---
- hosts: core_router
  become: yes
  gather_facts: yes
  tasks:
  - setup:

- hosts: vmware_fusion_host
  become: yes
  gather_facts: no
  connection: local
  tasks:
  - name: set-static-routes | check if route exists
    shell: >
      route -n get {{ (item.value.hostonly_subnet + '/' + item.value.hostonly_netmask) | ipaddr('net') }} | grep gateway
    with_dict: '{{ vmware_fusion_vmnets }}'
    when: item.value.virtual_adapter == 'no'
    register: _routes

  - name: set-static-routes | set static routes if needed
    command: >
      route add -net {{ (item.item.value.hostonly_subnet + '/' + item.item.value.hostonly_netmask) | ipaddr('net') }} {{ hostvars[groups.core_router[0]].ansible_default_ipv4.address }}
    with_items: '{{ _routes.results }}'
    when:
    - item.changed is true
    - hostvars[groups.core_router[0]].ansible_default_ipv4.address not in item.stdout
