---
- name: wait-for-ssh | wait for ssh
  become: false
  wait_for:
    port: 22
    host: '{{ inventory_hostname }}'
    search_regex: OpenSSH
    delay: 1
    timeout: 120
    sleep: 5
  vars:
    ansible_connection: local
