---
- name: nftables | install
  apt:
    name: nftables
    state: present

- name: nftables | template conf
  template:
    src: nftables.conf.j2
    dest: /etc/nftables.conf
    owner: root
    group: root
    mode: 0755
  notify: restart nftables

- name: nftables | systemd
  systemd:
    name: nftables
    state: started
    enabled: yes
