---
- name: bird2 | install bird
  yum:
    name: bird
    state: present

# This is a hilariously terrible. I cannot explain why a single 'setup' call is not sufficient.
- name: bird2 | gather facts if necessary
  setup:
  when: 'ansible_eth1.ipv4 is not defined'
  register: _bird2_force_facts
  retries: 5
  delay: 2
  until: _bird2_force_facts.ansible_facts.ansible_eth1.ipv4 is defined

- name: bird2 | template bird conf
  template:
    src: bird.conf.j2
    dest: /etc/bird.conf
    owner: root
    group: bird
    mode: 0640
  notify: restart bird2

- name: bird2 | sysctl
  sysctl:
    name: '{{ item.name }}'
    value: '{{ item.value }}'
  with_items:
  - name: net.ipv4.ip_forward
    value: 1
  - name: net.ipv4.conf.all.accept_redirects
    value: 0
  - name: net.ipv4.conf.all.send_redirects
    value: 0
  - name: net.ipv4.conf.default.send_redirects
    value: 0
  - name: net.ipv4.conf.eth0.send_redirects
    value: 0

- name: bird2 | systemd
  systemd:
    name: bird
    state: started
    enabled: yes

- name: bird2 | flush handlers
  meta: flush_handlers
