---
- name: network-interfaces-static | Debian
  include: debian.yaml
  when: 'ansible_distribution == "Debian"'

- name: network-interfaces-static | Fedora
  include: fedora.yaml
  when: 'ansible_distribution == "Fedora" or ansible_distribution == "CentOS"'
